### ISSUE TITLE
Adding movable and sortable feature.

### ISSUE THREAD

**Issue by dhaern** [teelolws/SLMicroMenu#1]
Hi, can you add a movable and sortable feature to micro menu + LFG eye + Bags frame/frames?

Like this pic as example:

[https://imgur.com/fqkOk2n](https://imgur.com/fqkOk2n)

**Comment by teelolws** [comment]
Dealing with the LFG Eye and Bags is outside of the scope of this addon. It deals with the menu buttons only.

**Comment by teelolws** [comment]
Check out this other project I'm working on: https://www.curseforge.com/wow/addons/edit-mode-expanded https://github.com/teelolws/EditModeExpanded

I'm not sure what you mean by "Sortable", but I've managed to hook moving the Micro Menu into Edit Mode. Resizing will come later, as well as support for the LFG Eye.
