### ISSUE TITLE
Goes invisible

### ISSUE THREAD

**Issue by Talimar** [teelolws/SLMicroMenu#10]
Been noticing the bar going invisible a lot last few days. Seems to be triggered by vehicles and possibly phasing.

![Wow_yyJ9dG3CnB](https://user-images.githubusercontent.com/21211868/204029553-e81948bd-f3ec-4f3e-ae9a-7f1cba5acf54.png)

**Comment by Talimar** [comment]
It still goes invisible in vehicles after update.

**Comment by teelolws** [comment]
Which vehicles? I tried the ones in Ulduar

**Comment by Talimar** [comment]
Just random vehicles during quests I guess. Like ones where you ride some dragon and have to throw stuff on the ground.
I could try to dig up a quest name if that helps.

**Comment by teelolws** [comment]
I've tried it with the vehicles from:
- the daily quest to use a drake in Coldarra (above the Nexus)
- the shredder in Gorgrond
- the tea tales world quest in Revendreth

In all cases so far, the menu just stays where it was while in a vehicle:
![image](https://user-images.githubusercontent.com/49792789/204368295-fcc366bd-bb23-4696-9a2c-67a88322ef12.png)

Can you confirm if it still happens with all other addons turned off? If it doesn't, can you work out which addon is causing interference?

**Comment by Talimar** [comment]
Will do. I keep forgetting to abandon quest to try again.

**Comment by Talimar** [comment]
Ok I hauled my ass over to Ulduar and it happens when Dominos is used with this addon.

**Comment by teelolws** [comment]
I'm trying it with just Dominos and SLMicroMenu enabled. Its the same as before - the menu buttons move into the Vehicle UI when I enter a vehicle, and move back to the bottom right corner again when I leave it.

SLMicroMenu has been programmed for a while to turn off most of its positioning features if it detects Dominos is installed. I'm not sure I can help.

**Comment by Talimar** [comment]
Is there anything I can do to help troubleshoot?

This is the specific settings I use for that bar if that matters.
![Wow_0SzUs9SEvE](https://user-images.githubusercontent.com/21211868/209338181-360d1ca8-9315-46f8-a663-94e23c00f96e.png)
![Wow_K1Iw22qCWD](https://user-images.githubusercontent.com/21211868/209338187-9b4021f4-e680-48d0-8051-2631d23554b9.png)

**Comment by teelolws** [comment]
I'm trying it with your settings, and I've noticed the menu bar goes invisible while in a vehicle, but reappears once I leave the vehicle. It does this when Dominos is the only addon I have installed!

So here, I'm not in a vehicle, you can see the menu button at bottom right:
![image](https://user-images.githubusercontent.com/49792789/210126584-f3bfcde1-e02d-425b-9cbc-b16615173a62.png)

After hopping in a vehicle:
![image](https://user-images.githubusercontent.com/49792789/210126586-61aa996c-133a-4ad5-8d4e-34665a5d2810.png)

And then I get out of the vehicle, the menu bar is back again:
![image](https://user-images.githubusercontent.com/49792789/210126594-4e2a318c-97bd-4c51-9f5d-a168869459a8.png)

If this is the same issue you are reporting, then its not my addon causing it. Its happening even without mine!

**Comment by Talimar** [comment]
Well sort of. The problem was with both of them installed your skin wouldn't return on exiting vehicle. But today it worked for some reason. Tested both ulduar and the new raid. So I think we can close this finally :)
