### ISSUE TITLE
Feature Request: Global Options

### ISSUE THREAD

**Issue by nancikennedy** [teelolws/SLMicroMenu#11]
Please make it possible to save the options per-account, rather than per-character.

**Comment by teelolws** [comment]
If you mean the Edit Mode settings of where the menu bar gets placed and its size, they're saved per Edit Mode profile, whether that is character or account.

Here I have 1 character-specific profile, 2 account-wide profiles, and the 2 preset profiles built into the game:
![image](https://user-images.githubusercontent.com/49792789/205465894-ebc5e896-9ac4-4577-93cd-f60913b0e999.png)

You can make an account-wide profile by just not checking this box:
![image](https://user-images.githubusercontent.com/49792789/205465911-f7eef25e-64ef-45aa-b44d-0b4852893532.png)

**Comment by nancikennedy** [comment]
I only use global edit mode layouts, but the micro menu settings are getting saved in my char saved variables folder not the account saved vars folder.

**Comment by teelolws** [comment]
Sorry, looks like I made it account-wide on https://github.com/teelolws/EditModeExpanded but never copied the fix over here.

**Comment by nancikennedy** [comment]
Gotta love it when that happens as a programmer. :)
