### ISSUE TITLE
Conflict with Elvui icons?

### ISSUE THREAD

**Issue by pcangelnc** [teelolws/SLMicroMenu#12]
Elvui recently updated to include their own microbar replacement icons. However, I prefer these to Elvui's (these mimic the old Blizzard ones, Elvui's uses different icons and some are just not intuitive to me).  I just can't figure out how to get them to work  together.  I think Elvui's overrides these but if I disable Elvui's the microbar disappears completely.  If in enable in Elvui, I either get the grey Blizzard ones or theirs.  Anyone have a way to get them to play nicely together?

**Comment by teelolws** [comment]
Best I can do. This is with Elvui set to Micro Bar Enabled and Use Icons Disabled. 

Theres only so far I can go with addon vs addon issues like this. Elvui is fighting to resize the icons and replace them with different icons, even when its set not to. If you disable the menu bar in Elvui, it fights to keep it hidden:

![image](https://user-images.githubusercontent.com/49792789/210127495-5fbd7969-0622-4eea-8dc5-97a06b8ac14b.png)

**Comment by pcangelnc** [comment]
I totally understand. I wasn't sure if there was anything that could be done, so appreciate the effort! Not sure why Elvui decided to use the icons they did-I find them confusing choices.
