### ISSUE TITLE
Seems to not be working after 10.0.5

### ISSUE THREAD

**Issue by Venomisto** [teelolws/SLMicroMenu#14]
Hi, updating the addon and logging in today the micromenu looks like the new version. I tried with Bartender4 enabled and without it enabled, didn't work for either. I see you have the addon bartender4 set as not compatible but it worked fine for me with bartender4 before today, was that just added today? Anyway it doesn't work for me with no addons but SLMicroMenu enabled after today either. Thanks.

Edit: Looks like they changed something with the micromenu, other addons having are issues with it too.

**Comment by teelolws** [comment]
Bartender hasn't been updated for 10.0.5 yet and is throwing errors related to the menu bar. For some reason, Blizzard turned off the scriptErrors CVar in 10.0.5 so you won't see the errors by default anymore.

Not getting any problems here with all other addons disabled. Can you see if you get an error, or step through the code and find where its breaking?

**Comment by Venomisto** [comment]
It was the first line of the addon still checking for 10.0.2 so I downloaded the file manually from curse to check and it seems the curseforge standalone app was pulling 10.0-017 as the latest version still. Checking even further it was doing it for a bunch of addons, I know they had a lot of issues with the site the past week so maybe it's related. Restarting the app fixed it. I should have checked that before posting sorry.

**Comment by teelolws** [comment]
All good. I suspected that might be it.
