### ISSUE TITLE
NOT SAVING RESIZE, BUT ONLY POSITION

### ISSUE THREAD

**Issue by lloskka** [teelolws/SLMicroMenu#15]
Hello, and good morning.

Since 10.0.5 we are able now to move and suposedly "resize" the SLMM on blizzard defaults.

It is saving position, but not resize .

Are you able to do something? or is it blizzard api fault.

Cheers.

**Comment by teelolws** [comment]
Blizzard took back control over the Edit Mode controls of the menu in 10.0.5. If there are issues with resizing, they're doing it, not me!

**Comment by lloskka** [comment]
oke doke! thank for the info

i was very annoyed anywhere i placed the bar, at the next char login account, it resets to its default size no matter what.
