### ISSUE TITLE
How to increase the width

### ISSUE THREAD

**Issue by Machou** [teelolws/SLMicroMenu#16]
Hello,

I think this addon is great, because I hate the new buttons...

But I find that each button is compressed, it lacks 5 pixels (maybe a little more); which line can I modify to increase the size of the buttons?

Regards

**Comment by teelolws** [comment]
This is a comparison picture I just made. On the top is WOTLK Classic, middle is 10.0.5 with the menu bar set to 150%, and the bottom is a screenshot of Shadowlands:
![image](https://user-images.githubusercontent.com/49792789/215590686-b6fe4fc8-1370-4ab2-97d4-4d6c1fb78720.png)

It looks like all the pictures are still the same without any compression, just the buttons are slightly wider now. I could maybe shave a pixel or two off the buttons width, but I worry that might cause problems with other addons if I do that.

**Comment by teelolws** [comment]
Comparing 10.0.5 code to 9.2.7, they changed the buttons from 28x36 to 19x26. You could drop that to 18x26 or 17x26 by adding this line, in SLMicroMenu.lua, at line 42:

`data.button:SetWidth(17)`

Comparison:
![image](https://user-images.githubusercontent.com/49792789/215593139-e7ae151a-1827-404b-9624-cc3766d6431d.png)

**Comment by Machou** [comment]
Actually, I find them too small with **SLMicroMenu**, but I put `data.button:SetWidth(22)` and it's perfect :) here is what it looks like:

![](https://i.ibb.co/N368k5R/Wo-WScrn-Shot-013023-234519.jpg)

I think it's better, but to each his own, I think :)

just a little problem with the quest icon when I move my mouse over it, if you know how to leave it at the same size as all the others?

![](https://i.ibb.co/hyWfpY1/Wo-WScrn-Shot-013023-234934.jpg)

**Comment by teelolws** [comment]
Must be some other addon doing that.
![image](https://user-images.githubusercontent.com/49792789/215616427-acaef7b3-ef58-4f5f-babe-7c6dc7d7987d.png)

**Comment by Machou** [comment]
I'm not talking about the tooltip, but the icon. Can't you see that it's unpacked? The addon is Classic Quest, but that has nothing to do with it.

**Comment by teelolws** [comment]
The picture I showed is while I'm mousing over the Quest button. I'm not seeing any problems with the icon.

**Comment by Machou** [comment]
> The picture I showed is while I'm mousing over the Quest button. I'm not seeing any problems with the icon.

This is normal, because I put **data.button:SetWidth(22)** on line 42

Anyway I deactivated the addon because it breaks too many things for few improvements, too bad =(
