### ISSUE TITLE
Blocks Actions like using spells

### ISSUE THREAD

**Issue by TPetersen5171** [teelolws/SLMicroMenu#19]
Every so often i get blocked from casting spells at the start of fights, has happened multiple times now, do not like having to reload ui all the time, and is super bad when its a same level creature, and come back after reload and my character is dead

**Comment by teelolws** [comment]
Thanks for the report. Unfortunately I cannot reproduce the issue.

Addon blocked errors can be very difficult to fix. Can you find a series of actions that always cause the issue to happen? And then, can you test if it happens while all your other addons are turned off?
