### ISSUE TITLE
Bag UI visible even when deactivated with Bartender4

### ISSUE THREAD

**Issue by Flanell88** [teelolws/SLMicroMenu#2]
The new version displays the bag ui even when I deactivated them with bartender4.

**Comment by teelolws** [comment]
Its on my list to add an option to hide it during Edit Mode: https://github.com/teelolws/EditModeExpanded/issues/5

In the meantime, just use 

    /run EditModeExpandedBackpackBar:Hide()
    
to make it go away.

The proper fix will be up ASAP! I plan to work on it tomorrow.

**Comment by teelolws** [comment]
Uploading a new version now. You'll have the option to hide the backpack bar:

![image](https://user-images.githubusercontent.com/49792789/200071195-7d43124c-27e4-4203-a2e2-a5f50ee8cad2.png)
![image](https://user-images.githubusercontent.com/49792789/200071237-6c2b7b27-9c9e-4ec5-8c27-2d5d01bc7506.png)
![image](https://user-images.githubusercontent.com/49792789/200071247-e1326ff8-5227-46fc-93b5-a7daa6db160a.png)
