### ISSUE TITLE
Possibility to bring 10.0-10.1.5 micro menu?

### ISSUE THREAD

**Issue by kneekicker** [teelolws/SLMicroMenu#20]
With the latest changes to micro menu once again in 10.1.5. Would you be interested in making a spin-off of this addon to bring the grayish micro menu from the start of dragonflight back?

**Comment by teelolws** [comment]
I tried working on this last week, but its a lot more complicated than the Shadowlands menu. The Shadowlands menu is still in the game, this addon just swaps all the atlases back. Unfortunately, Blizzard completely removed the gray menu data from the game. So I will have to recreate everything all over again. I plan to finish it when I have time!

**Comment by teelolws** [comment]
Okay, I've added it as an option to one of my other addons: https://www.curseforge.com/wow/addons/edit-mode-expanded

You'll be able to switch to it during edit mode:
![image](https://github.com/teelolws/SLMicroMenu/assets/49792789/770189b2-6479-4584-b759-bd42e454557f)
![image](https://github.com/teelolws/SLMicroMenu/assets/49792789/c3980c78-acef-4065-a2be-82d9c8d17cf4)

Try not to turn on both at the same time.
