### ISSUE TITLE
Feature / MicroAddon Request.

### ISSUE THREAD

**Issue by Ziggy815** [teelolws/SLMicroMenu#21]
Hi! I have seen your two addons and i am searching a mix of both :)
Is it possible to just make a micro addon that only allows to change the size of the mini menu to its old site before the last patch from blizzard made it a mess ?

**Comment by teelolws** [comment]
Hi, what if you just use my Edit Mode Expanded addon but turn off all the modules you don't want to use?

Like this, in your interface options:
![image](https://github.com/teelolws/SLMicroMenu/assets/49792789/5a0fe07c-2288-4fc4-a002-a130a4b07fa7)

**Comment by Ziggy815** [comment]
Hey there,

thanks for you quickl replay!

The problem is that i want to scale the bar smaller than 100%. The zeropadding almost did it but as you see in the pic it still overlaps. But if its too much work / trouble, just forget it, i am happy that you addon exist so that i can at least scale it a little :) 

![WoWScrnShot_092923_230748](https://github.com/teelolws/SLMicroMenu/assets/40720477/b4acef15-b2bc-4a38-b8ac-ef4d7487229c)

**Comment by teelolws** [comment]
Oh right. Yup that options there, you just have to turn it on!
![image](https://github.com/teelolws/SLMicroMenu/assets/49792789/a7b8b2a8-f078-4566-a20a-fc345db01511)

**Comment by Ziggy815** [comment]
OMG sorry lol, now i am feeling just "a little" stupid, havent seen that :) ... Thanks, it now works like a charm!
