### ISSUE TITLE
Guild Button is blank

### ISSUE THREAD

**Issue by Guino13** [teelolws/SLMicroMenu#22]
The Guild button in the new version for 10.2 is blank on all 7 of my toons.  Please take a look as to why and update.

Thank you.

**Comment by teelolws** [comment]
I'm getting this too, but its happening even without the addon. The guild logo isn't loading in, even on other parts of the UI.

Looks like Blizzard knows about it: https://us.forums.blizzard.com/en/wow/t/known-issue-guild-crests/1704691

**Comment by teelolws** [comment]
They (finally) fixed it.
