### ISSUE TITLE
High cpu usage 

### ISSUE THREAD

**Issue by Talimar** [teelolws/SLMicroMenu#23]
Just ran a test with addon cpu usage in lfr and this addon was quite high for what it does:

![E6GpSFCvpZ](https://github.com/teelolws/SLMicroMenu/assets/21211868/12aed2a1-19bb-4bfd-a365-4945e5977528)

I have no idea if it actually impacts performance much.

**Comment by teelolws** [comment]
The base UI is constantly trying to change some of the textures back to the Dragonflight variants. My addon has to immediately change them again which takes up some processing time. This happens many times a second.

This change should cut down some of the processing it does. The profiler has it down from 15ms per second to 3ms per second from the testing I did.
