### ISSUE TITLE
No longer works as of SLMicroMenu-10.0-004

### ISSUE THREAD

**Issue by mbecknc** [teelolws/SLMicroMenu#3]
1x FrameXML\Bindings.xml:1 FrameXML\Bindings.xml:9 Couldn't open Interface/AddOns/SLMicroMenu/libs/EditModeExpanded-1.0/EditModeExpanded-1.0.xml

1x Interface/AddOns/SLMicroMenu/SLMicroMenu.lua:3: Cannot find a library instance of "EditModeExpanded-1.0".
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/AskMrRobot/Libs/LibStub/LibStub.lua"]:23: in function `GetLibrary'
[string "@Interface/AddOns/SLMicroMenu/SLMicroMenu.lua"]:3: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "EditModeExpanded-1.0"."

**Comment by teelolws** [comment]
It looks like whatever you used to install the addon, didn't install all the files. Can you force a reinstall?
