### ISSUE TITLE
Bags appear because of SLMicroMenu

### ISSUE THREAD

**Issue by vince2paname** [teelolws/SLMicroMenu#6]
One of the issue appeared on version 10.0-003 and superior is the appearance of the bags.
It seems to be intended, but unfortunatly, it's an issue for those who do not want these bags to appear.
Is it possible to get an option to hide bags, like it was on version 10.0-001 ? I'm still using the first version, the only one working correctly, without the bags to appear.

Thank you.

**Comment by teelolws** [comment]
Yes, the option is there. Go into Edit Mode, select the bags, and hide them.

**Comment by vince2paname** [comment]
It doesn't work. Even when hide is checked, it's still visible.
By default, I don't see the bags because I use ELVUI. They started to appear with SLMicroMenu, because it seems that in the code you have added a few lines to make it appear. The first version is just fine, others don't work as intented, showing bags even when it's not requested.

Edit : After I restarted the game, it worked. Thank you.

**Comment by teelolws** [comment]
I found a bug that will show the bar again after exiting Exit Mode. Current workaround is to do a quick /reload to make it respect your Hide option.
