### ISSUE TITLE
New update broke the addon

### ISSUE THREAD

**Issue by Bryaniame** [teelolws/SLMicroMenu#7]
After the new update ([Version 11 for 10.0.2) literally broke the whole addon. Micro bar is back to the gray dragonflight version.
Maybe test your update before push? xd

**Comment by teelolws** [comment]
Maybe don't install a 10.0.2 version on 10.0.0?

**Comment by ablib2** [comment]
> Maybe don't install a 10.0.2 version on 10.0.0?

Don't understand this reply.  The addon is broke, no matter how you install.
